export enum QueueInjectionTokens {
  // Kafka services
  KAFKA_ORCHESTRATOR = 'KAFKA_ORCHESTRATOR',
  KAFKA_PENDING_REQUESTS_SERVICE = 'KAFKA_PENDING_REQUESTS_SERVICE',
  KAFKA_CONSUMER_SERVICE = 'KAFKA_CONSUMER_SERVICE',
  KAFKA_PRODUCER_SERVICE = 'KAFKA_PRODUCER_SERVICE',
  KAFKA_CONSUMER_REGISTRY = 'KAFKA_CONSUMER_REGISTRY',
  
  // SSE services
  SSE_NOTIFICATION_SERVICE = 'SSE_NOTIFICATION_SERVICE',
  
  // Health and monitoring
  KAFKA_HEALTH_SERVICE = 'KAFKA_HEALTH_SERVICE',
  
  // Handlers
  REPLY_TOPIC_HANDLER = 'REPLY_TOPIC_HANDLER',
  TASK_NOTIFICATION_HANDLER = 'TASK_NOTIFICATION_HANDLER',
}
