export enum NestjsInjectionToken {
    REQUEST_STORAGE = 'REQUEST_STORAGE',
    REQUEST_STORAGE_MIDDLEWARE = 'REQUEST_STORAGE_MIDDLEWARE',
    CATCH_FILTER = 'CATCH_FILTER',
    QUERY_RUNNER_MANAGER = "QUERY_RUNNER_MANAGER",
    METRICS_INTERCEPTOR = "METRICS_INTERCEPTOR",
}